### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by katbon** [katbon/fosdem-video-update-notification#1]
Use Python requests library to scrape video.fosdem.org/2015/ once every hour. Once the URL no longer returns a status code of 404 use Twilio to send a text message that contains the URL and a description of the URL.

**Comment by elimisteve** [comment]
Remaining:
- [x] See if `body` can be a tuple or whether it must be a string
- [x] Make sure `message` is being sent -- and being sent when it should be
- [x] Change `url` to point to the `2014` directory instead of `2015`, and run the app so that I get an SMS message
- [x] Tag this working version as `v1` once it's correctly sending texts

**Comment by katbon** [comment]
Fixed in commit daf177b
